spring.application.name=disasterguard

spring.datasource.url=jdbc:postgresql://localhost:5432/disasterguard
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=disasterguard_super_secret_key_123456789_must_be_long
jwt.expiration=86400000

server.port=8080