spring.application.name=disasterguard

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/disasterguard}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:disasterguard_super_secret_key_123456789_must_be_long}
jwt.expiration=86400000